deploy main (#5)

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,7 +1,7 @@
 name: 'Deploy'
 on:
   push:
-    branches: [ $default-branch ]
+    branches: [ main ]
 pull_request:
 
 permissions:
@@ -22,5 +22,5 @@ jobs:
         uses: actions/checkout@v3
       - name: No going back now
         run: echo "I am deploying"
-      - name: Fail
-        run: exit 1
+#      - name: Fail
+#        run: exit 1
